---
title: "Homework 4"
subtitle: "Data Cleaning & Prep Steps Provided by: Ashwin Malshe"
author: "Samuel Cynamon | yjj265"
date: "2023-11-11"
format:
  html: 
    embed-resources: TRUE
    toc: TRUE
    toc-location: left
    toc_depth: 4
---

```{r setup, message=FALSE}
library(tidyverse)
library(here)
library(readr)
```

### Download the Data

```{r}
ele_2020 <- read_csv("https://raw.githubusercontent.com/tonmcg/US_County_Level_Election_Results_08-20/master/2020_US_County_Level_Presidential_Results.csv")
ele_2016 <- read_csv("https://raw.githubusercontent.com/tonmcg/US_County_Level_Election_Results_08-20/master/2016_US_County_Level_Presidential_Results.csv")
```

```{r}
names(ele_2016)
```

```{r}
names(ele_2020)
```

### Mutate the Raw Data

```{r}
ele_2016 <- ele_2016 %>%
  select(-1, -per_point_diff, -county_name, -diff) %>%
  mutate(combined_fips = sprintf("%05d", combined_fips)) %>%
  rename(votes_dem_16 = votes_dem,
         votes_gop_16 = votes_gop,
         total_votes_16 = total_votes,
         per_dem_16 = per_dem,
         per_gop_16 = per_gop
  )
```

```{r}
ele_2020 <- ele_2020 %>%
  select(-diff) %>%
  rename(votes_dem_20 = votes_dem,
         votes_gop_20 = votes_gop,
         total_votes_20 = total_votes,
         per_dem_20 = per_dem,
         per_gop_20 = per_gop,
         per_point_diff_20 = per_point_diff
  )
```

```{r}
total_election <- ele_2020 %>% left_join(ele_2016, by = c("county_fips" = "combined_fips"))
```

### End Result

```{r include=FALSE}
knitr::kable(total_election)
```

```{r}
total_election %>% 
  arrange(state_name)
```

```{r include=FALSE}
write.csv(total_election, "election_16_20.csv", row.names=FALSE)
```

